// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWheyh2-GQGKHz-HXGPInPi3Y6vD8i1XU',
    appId: '1:444724552872:web:b93980d855d8a57af2ce9d',
    messagingSenderId: '444724552872',
    projectId: 'fooddelivery-b432e',
    authDomain: 'fooddelivery-b432e.firebaseapp.com',
    storageBucket: 'fooddelivery-b432e.firebasestorage.app',
    measurementId: 'G-Z1C9YM6TJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC11RkOJOW2KXE2ozEIo7q_hOoPf4iVZhc',
    appId: '1:444724552872:android:b17031ec47802868f2ce9d',
    messagingSenderId: '444724552872',
    projectId: 'fooddelivery-b432e',
    storageBucket: 'fooddelivery-b432e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnZstiBgNQ25vYCob9-Jkc9RasWkSMvN4',
    appId: '1:444724552872:ios:f40cf1cfcc101022f2ce9d',
    messagingSenderId: '444724552872',
    projectId: 'fooddelivery-b432e',
    storageBucket: 'fooddelivery-b432e.firebasestorage.app',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnZstiBgNQ25vYCob9-Jkc9RasWkSMvN4',
    appId: '1:444724552872:ios:f40cf1cfcc101022f2ce9d',
    messagingSenderId: '444724552872',
    projectId: 'fooddelivery-b432e',
    storageBucket: 'fooddelivery-b432e.firebasestorage.app',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWheyh2-GQGKHz-HXGPInPi3Y6vD8i1XU',
    appId: '1:444724552872:web:59cee2f6c9c87998f2ce9d',
    messagingSenderId: '444724552872',
    projectId: 'fooddelivery-b432e',
    authDomain: 'fooddelivery-b432e.firebaseapp.com',
    storageBucket: 'fooddelivery-b432e.firebasestorage.app',
    measurementId: 'G-6Z3F69WQ4B',
  );
}
